# Relatório de Análise IV

## Seleções e Frequêncais

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('Dados/aluguel_residencial.csv',sep=';')

In [3]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
8,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0

In [5]:
# Selecione somente Imóveis classificados com tipo 'Apartamento'
selecao = dados['Tipo'] == 'Apartamento'
n1 = dados[selecao]
n1

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
8,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
15,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
17,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
21,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
22,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
23,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
26,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
27,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
28,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
29,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
31,Apartamento,Jardim Oceânico,3,3,1,200,3500.0,1780.0,496.0
32,Apartamento,Barra da Tijuca,3,1,2,70,1800.0,1095.0,140.0
33,Apartamento,Copacabana,4,1,0,244,5000.0,2500.0,4100.0
34,Apartamento,Barra da Tijuca,3,2,1,110,4500.0,2000.0,450.0
35,Apartamento,Recreio dos Bandeirantes,2,2,2,90,3000.0,1340.0,NaN
36,Apartamento,Recreio dos Bandeirantes,3,2,2,100,2600.0,380.0,NaN
37,Apartamento,Barra da Tijuca,3,1,1,72,2350.0,600.0,70.0
38,Apartamento,Humaitá,2,2,1,180,4000.0,2500.0,300.0
...,...,...,...,...,...,...,...,...,...
22543,Apartamento,Olaria,2,0,0,67,1250.0,150.0,NaN
22544,Apartamento,Botafogo,3,2,1,100,4500.0,1600.0,205.0
22546,Apartamento,Lagoa,3,3,1,225,12000.0,3756.0,977.0
22548,Apartamento,Flamengo,1,0,0,48,2200.0,478.0,NaN
22549,Apartamento,Copacabana,2,0,0,67,2450.0,679.0,80.0
22550,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
22552,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
22553,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
22559,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
22560,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
22562,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
22564,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
22567,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
22571,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
22572,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
22573,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [14]:
# Selecione Imóveis classificados com tipos 'Casa', 'Casa de Condomínio' e 'Casa de Vila'
selecao = (dados['Tipo'] == 'Casa') | (dados['Tipo'] == 'Casa de Condomínio') | (dados['Tipo'] == 'Casa de Vila')
n2 = dados[selecao]
n2

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
14,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
18,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
24,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
44,Casa de Condomínio,Barra da Tijuca,5,10,5,1600,25000.0,1600.0,NaN
56,Casa,Méier,2,0,0,51,1500.0,50.0,NaN
60,Casa,São Conrado,4,2,4,730,28000.0,2000.0,12000.0
61,Casa de Condomínio,Freguesia (Jacarepaguá),5,3,1,140,2500.0,1200.0,NaN
85,Casa de Vila,Piedade,2,1,0,70,1300.0,NaN,NaN
100,Casa,Maracanã,8,3,5,259,7000.0,NaN,NaN
104,Casa,Benfica,1,0,0,33,1200.0,NaN,NaN
150,Casa,Jardim Carioca,3,2,1,135,3000.0,NaN,NaN
166,Casa,Lins de Vasconcelos,2,0,0,40,950.0,NaN,50.0
172,Casa de Condomínio,Barra da Tijuca,4,2,4,595,30000.0,2500.0,2510.0
174,Casa de Condomínio,Recreio dos Bandeirantes,4,4,4,267,6500.0,700.0,3308.0
188,Casa,Tijuca,4,1,1,191,4000.0,300.0,NaN
191,Casa de Condomínio,São Conrado,3,2,1,250,5500.0,750.0,500.0
217,Casa de Condomínio,Barra da Tijuca,4,4,4,1000,30000.0,2695.0,23715.0
222,Casa de Vila,Jardim Sulacap,2,1,2,115,1600.0,1.0,60.0
230,Casa de Vila,Oswaldo Cruz,1,0,1,40,800.0,NaN,NaN
232,Casa de Condomínio,Freguesia (Jacarepaguá),2,1,0,163,1800.0,92.0,46.0
248,Casa,Grajaú,5,4,2,450,7000.0,NaN,500.0
256,Casa de Condomínio,Vargem Grande,2,2,1,90,1700.0,618.0,338.0
260,Casa,Tanque,2,1,0,59,1200.0,170.0,NaN
263,Casa,Campo Grande,3,0,0,200,2100.0,NaN,NaN
269,Casa de Condomínio,Barra da Tijuca,5,6,5,640,13800.0,980.0,1800.0
274,Casa,Bonsucesso,2,0,0,51,1000.0,NaN,NaN
275,Casa de Condomínio,Barra da Tijuca,5,3,5,1000,20000.0,1800.0,1800.0
...,...,...,...,...,...,...,...,...,...
22332,Casa,Andaraí,3,1,0,75,2950.0,NaN,NaN
22338,Casa de Vila,Quintino Bocaiúva,2,0,0,58,1000.0,NaN,NaN
22357,Casa,Lagoa,3,3,1,250,8600.0,1900.0,580.0
22365,Casa,Engenho Novo,1,0,0,40,450.0,NaN,NaN
22368,Casa de Condomínio,Leblon,6,3,6,1206,55000.0,3200.0,5016.0
22383,Casa de Condomínio,Copacabana,2,1,1,80,3000.0,50.0,NaN
22387,Casa de Vila,Todos os Santos,3,1,1,92,1500.0,80.0,11.0
22396,Casa de Condomínio,Recreio dos Bandeirantes,4,4,4,350,9000.0,550.0,3000.0
22420,Casa,Maracanã,4,2,1,240,6500.0,NaN,700.0
22425,Casa,Campo Grande,2,1,2,86,1500.0,NaN,NaN
22444,Casa de Condomínio,Barra da Tijuca,5,3,5,900,20000.0,1300.0,1600.0
22446,Casa de Condomínio,Barra da Tijuca,3,3,3,400,7500.0,1900.0,NaN
22451,Casa de Condomínio,Itanhangá,3,2,3,200,3600.0,480.0,NaN
22452,Casa,Vila da Penha,2,1,0,80,1500.0,NaN,NaN
22462,Casa de Condomínio,Recreio dos Bandeirantes,4,4,3,500,9000.0,1000.0,900.0
22464,Casa de Condomínio,Barra da Tijuca,4,4,2,600,30000.0,1050.0,NaN
22469,Casa de Vila,Riachuelo,3,0,0,73,850.0,NaN,NaN
22472,Casa de Condomínio,Barra da Tijuca,4,3,4,300,10000.0,1055.0,5500.0
22506,Casa de Condomínio,Barra da Tijuca,4,2,4,290,7000.0,7068.0,6800.0
22510,Casa,Campo Grande,1,0,0,50,600.0,NaN,NaN
22516,Casa de Vila,Pavuna,2,0,0,55,600.0,NaN,NaN
22517,Casa de Condomínio,Barra da Tijuca,4,3,2,250,7500.0,1300.0,680.0
22518,Casa de Condomínio,Barra da Tijuca,4,3,4,460,12000.0,1000.0,1200.0
22535,Casa,Recreio dos Bandeirantes,4,2,2,352,6500.0,NaN,NaN
22536,Casa de Condomínio,Barra da Tijuca,5,2,5,554,20000.0,1892.0,1743.0
22545,Casa de Condomínio,Freguesia (Jacarepaguá),3,3,1,155,2000.0,530.0,1250.0
22547,Casa,Bento Ribeiro,2,1,0,60,1400.0,NaN,NaN
22555,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
22558,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
22574,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0

In [16]:
# Selecione os Imóveis com área entre 60 e 100 metros quadrados, incluindo os limites
selecao = (dados['Area'] >= 60) & (dados['Area'] <= 100)
n3 = dados[selecao]
n3

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
32,Apartamento,Barra da Tijuca,3,1,2,70,1800.0,1095.0,140.0
35,Apartamento,Recreio dos Bandeirantes,2,2,2,90,3000.0,1340.0,NaN
36,Apartamento,Recreio dos Bandeirantes,3,2,2,100,2600.0,380.0,NaN
37,Apartamento,Barra da Tijuca,3,1,1,72,2350.0,600.0,70.0
39,Apartamento,Recreio dos Bandeirantes,3,1,2,92,2300.0,840.0,200.0
43,Apartamento,Recreio dos Bandeirantes,2,1,2,83,1600.0,1160.0,157.0
47,Apartamento,Ipanema,3,1,0,87,3200.0,1305.0,217.0
48,Apartamento,Méier,3,1,0,90,1550.0,844.0,80.0
51,Apartamento,Maracanã,2,0,0,86,1800.0,600.0,82.0
52,Apartamento,Recreio dos Bandeirantes,2,1,1,74,1850.0,675.0,200.0
53,Apartamento,Jacarepaguá,3,1,1,74,1900.0,556.0,98.0
57,Apartamento,Jardim Botânico,2,2,0,95,4000.0,1170.0,NaN
58,Apartamento,Barra da Tijuca,2,1,1,70,NaN,970.0,68.0
59,Apartamento,Cachambi,2,0,0,60,1000.0,380.0,280.0
62,Apartamento,Leblon,2,1,1,80,3500.0,990.0,245.0
66,Apartamento,Gávea,2,1,0,70,2800.0,680.0,98.0
67,Apartamento,Barra da Tijuca,2,1,1,88,2700.0,1300.0,2042.0
70,Apartamento,Bonsucesso,2,1,0,77,1500.0,740.0,NaN
71,Apartamento,Barra da Tijuca,3,2,2,85,2500.0,1400.0,190.0
72,Apartamento,Todos os Santos,3,1,1,78,1450.0,630.0,73.0
75,Apartamento,Jacarepaguá,2,1,1,69,2000.0,780.0,NaN
...,...,...,...,...,...,...,...,...,...
22500,Apartamento,Botafogo,2,1,2,84,4230.0,1130.0,260.0
22503,Apartamento,Méier,2,1,0,64,1100.0,644.0,NaN
22504,Apartamento,Recreio dos Bandeirantes,2,1,1,80,1500.0,746.0,83.0
22507,Apartamento,Barra da Tijuca,2,1,1,100,3500.0,985.0,230.0
22509,Apartamento,Recreio dos Bandeirantes,2,1,1,80,1700.0,450.0,138.0
22513,Apartamento,Irajá,2,1,0,62,1000.0,300.0,NaN
22524,Apartamento,Leblon,2,0,0,73,3000.0,500.0,284.0
22525,Apartamento,Barra da Tijuca,2,1,1,72,1700.0,870.0,160.0
22527,Apartamento,Tijuca,3,1,0,75,1900.0,860.0,141.0
22529,Apartamento,Taquara,2,1,1,71,1300.0,470.0,NaN
22532,Apartamento,Freguesia (Jacarepaguá),2,1,1,87,1300.0,869.0,77.0
22537,Apartamento,Copacabana,1,0,0,60,2400.0,530.0,78.0
22539,Apartamento,Leblon,2,1,1,90,10500.0,23511.0,352.0
22543,Apartamento,Olaria,2,0,0,67,1250.0,150.0,NaN
22544,Apartamento,Botafogo,3,2,1,100,4500.0,1600.0,205.0
22547,Casa,Bento Ribeiro,2,1,0,60,1400.0,NaN,NaN
22549,Apartamento,Copacabana,2,0,0,67,2450.0,679.0,80.0
22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [18]:
# Selecione os Imóveis que tenham pelo menos 4 quartos e aluguel menor que R$ 2.000,00
selecao = (dados['Quartos'] >= 4) & (dados['Valor'] < 2000.00)
n4 = dados[selecao]
n4

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
484,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,830.0,NaN
1003,Apartamento,Taquara,4,1,1,110,1900.0,NaN,NaN
1961,Casa,Campo Grande,4,1,4,100,1600.0,NaN,NaN
2102,Casa,Engenho de Dentro,4,3,0,120,1500.0,NaN,NaN
2200,Apartamento,Recreio dos Bandeirantes,4,2,2,125,1700.0,NaN,90.0
2338,Casa de Vila,Méier,4,0,1,85,1600.0,NaN,NaN
3943,Casa,Campo Grande,4,1,0,140,1700.0,NaN,NaN
3944,Apartamento,Campo Grande,4,2,1,115,1900.0,500.0,NaN
4349,Apartamento,Recreio dos Bandeirantes,4,2,1,105,1900.0,1492.0,205.0
5081,Apartamento,Cidade Nova,4,0,0,110,1300.0,NaN,NaN
6524,Apartamento,Pechincha,4,1,2,178,1900.0,1100.0,270.0
6800,Casa,Riachuelo,4,0,1,100,1800.0,NaN,40.0
6811,Casa,Méier,4,1,1,125,1900.0,NaN,NaN
7624,Apartamento,Recreio dos Bandeirantes,4,2,3,280,1800.0,1400.0,580.0
7651,Apartamento,Recreio dos Bandeirantes,4,3,2,250,1500.0,1380.0,700.0
7867,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1093.0,183.0
10111,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1038.0,158.0
10929,Casa de Condomínio,Taquara,4,1,0,110,1750.0,550.0,993.0
11308,Casa,Santo Cristo,5,0,0,85,1200.0,NaN,NaN
11977,Apartamento,Leme,4,0,1,185,1800.0,2000.0,270.0
12525,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,930.0,150.0
13307,Apartamento,Camorim,4,1,1,96,1350.0,747.0,NaN
13659,Apartamento,Barra da Tijuca,4,3,4,148,1600.0,1766.0,NaN
14034,Casa,Praça Seca,4,1,1,128,1600.0,NaN,228.0
14987,Casa de Condomínio,Freguesia (Jacarepaguá),4,2,1,120,1800.0,195.0,30.0
15010,Casa,Pedra de Guaratiba,4,1,0,100,1300.0,NaN,NaN
15912,Apartamento,Campo Grande,4,2,2,160,1900.0,880.0,NaN
16031,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,912.0,160.0
16137,Apartamento,Rio Comprido,4,1,0,110,1650.0,500.0,NaN
16791,Casa,Campo Grande,4,3,0,120,1700.0,NaN,NaN
17764,Apartamento,Taquara,4,3,1,190,1200.0,NaN,NaN
17884,Casa,Campo Grande,4,0,1,366,1890.0,NaN,208.0
18140,Casa,Campo Grande,4,0,0,159,1800.0,NaN,NaN
18274,Casa,Braz de Pina,4,1,0,99,1800.0,NaN,NaN
18453,Casa,Campo Grande,4,1,3,100,1600.0,NaN,NaN
19403,Casa,Campo Grande,4,1,2,180,1850.0,300.0,NaN
20178,Apartamento,Campo Grande,4,1,1,80,1600.0,950.0,NaN
20974,Apartamento,Barra da Tijuca,4,3,4,148,1500.0,1600.0,196.0
21475,Apartamento,Vargem Grande,4,0,1,180,1900.0,NaN,176.0
21783,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,1038.0,NaN
21938,Casa,Campo Grande,4,2,0,120,1600.0,NaN,NaN